apiVersion: v1
kind: Service
metadata:
  name: wazuh-enroll
  namespace: wazuh
  labels:
    app: wazuh-manager
spec:
  selector:
    app: wazuh-manager
    node-type: master
  ports:
    - name: registration
      protocol: TCP
      port: 1514
      targetPort: 1514